# Lab 4

In [5]:
x = 5
def testF():
    print(5)
testF()

5


In [2]:
import numpy as np

### Exercise 1:

Create an one dimensional array x with 100 integers, each integer is randomly selected from 0-9 with equal probability.

In [2]:
#hint
np.random.randint?

In [4]:
#Todo
# x=np.array(np.random.randint(0,10,100))
x = np.random.randint(0,10,100)

numpy.ndarray

### Exercise 2: 

Reverse the elements in x, i.e., first element becomes last, and so on...

In [4]:
#TODO for exercise 2
x[::-1]

array([9, 9, 9, 0, 1, 9, 4, 4, 2, 1, 2, 5, 4, 0, 0, 8, 6, 4, 1, 7, 9, 3,
       0, 8, 7, 0, 7, 6, 9, 3, 5, 1, 8, 7, 9, 2, 8, 7, 9, 5, 5, 7, 0, 0,
       1, 9, 1, 8, 8, 3, 1, 8, 0, 5, 1, 9, 4, 5, 6, 4, 3, 3, 7, 3, 3, 1,
       1, 8, 9, 1, 6, 3, 6, 7, 0, 3, 8, 0, 8, 6, 9, 2, 3, 0, 2, 8, 9, 1,
       5, 0, 7, 3, 2, 1, 3, 6, 8, 3, 6, 7])

### Exercise 3:

Find indices of non-zero elements from x, and put the indices into variable y.
How many elements in your array x are non-zeros?

In [5]:
#Hint
np.nonzero?

In [6]:
#TODO for exercise 3
# indices of non-zero elements
y = x.nonzero()
print(y)
#count elements in  array x which are non-zeros
np.count_nonzero(x)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 17, 18,
       19, 20, 21, 23, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 48, 49, 50, 51, 52, 53, 54, 55,
       58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 75,
       76, 78, 79, 80, 81, 82, 83, 84, 87, 88, 89, 90, 91, 92, 93, 94, 95,
       97, 98, 99]),)


88

### Exercise 4:

Find the mean of the original random array x.

In [7]:
#TODO for exercise 4
np.mean(x)

4.54

### Exercise 5:

Count how many elements are larger than 5 (>5) in the array of x

In [8]:
# Todo for exercise 5
np.count_nonzero(x>5)
# np.sum(x>5)

43

### Exercise 6

Reshape the array x into a two dimensional 10x10 matrix, and calculate the square root of each element, save the result to another 10x10 matrix z.

In [9]:
#TODO for exercise 6
#reshape
y = x.reshape((10,10))
#calculate the square root of each element
z = np.sqrt(y)
z

array([[2.64575131, 2.44948974, 1.73205081, 2.82842712, 2.44948974,
        1.73205081, 1.        , 1.41421356, 1.73205081, 2.64575131],
       [0.        , 2.23606798, 1.        , 3.        , 2.82842712,
        1.41421356, 0.        , 1.73205081, 1.41421356, 3.        ],
       [2.44948974, 2.82842712, 0.        , 2.82842712, 1.73205081,
        0.        , 2.64575131, 2.44948974, 1.73205081, 2.44948974],
       [1.        , 3.        , 2.82842712, 1.        , 1.        ,
        1.73205081, 1.73205081, 2.64575131, 1.73205081, 1.73205081],
       [2.        , 2.44948974, 2.23606798, 2.        , 3.        ,
        1.        , 2.23606798, 0.        , 2.82842712, 1.        ],
       [1.73205081, 2.82842712, 2.82842712, 1.        , 3.        ,
        1.        , 0.        , 0.        , 2.64575131, 2.23606798],
       [2.23606798, 3.        , 2.64575131, 2.82842712, 1.41421356,
        3.        , 2.64575131, 2.82842712, 1.        , 2.23606798],
       [1.73205081, 3.        , 2.4494897

### Exercise 7

Find out all the elements that are larger than 1 in z, replace them with 1.

In [10]:
# Todo for exercise 7
# Hint: use fancy indexing 
z[z>1] =1
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 0., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.]])

### Exercise 8

For the "count rainy days in seatle" example in lecture notes, do the following:
1. What's the percentage of rainy days in year 2014 in seatle?
2. How many days are rainy but with less than 0.3 inches rain?
3. Suppose autumn is from Sept. 20 to Dec. 22, what is the MEAN precipitation in autum 2014 in seatle? And what is the MEAN precipitation in RAINY, NON-AUTUMN days in seatle 2014? 

In [11]:
import numpy as np
import pandas as pd

# use pandas to extract rainfall inches as a NumPy array
rainfall = pd.read_csv('../Numpy/Seattle2014.csv')['PRCP'].values
inches = rainfall / 254.0  # 1/10mm -> inches

#Todo for exercise 8
#1
rainy_days_num = np.count_nonzero(inches> 0)
print("The percentage of rainy days in year 2014 in seatle: ","{:.2%}".format(rainy_days_num/365))
#2
smalllrain_days = np.sum((inches>0) & (inches < 0.3))
print("The number of days are rainy but with less than 0.3 inches rain: ", smalllrain_days)
#3
days = np.arange(365)
autumn = (days>262)&(days<355)
rainy_days = (inches > 0)

precipitation_autumn=np.mean(inches[autumn])
print("MEAN precipitation in autumn 2014 in seatle: ",precipitation_autumn)
precipitation_rainy_nonautumn=np.mean(inches[rainy_days &~autumn])
print("MEAN precipitation in RAINY, NON-AUTUMN days in seatle 2014: ", precipitation_rainy_nonautumn)

The percentage of rainy days in year 2014 in seatle:  41.10%
The number of days are rainy but with less than 0.3 inches rain:  92
MEAN precipitation in autumn 2014 in seatle:  0.18657993837726802
MEAN precipitation in RAINY, NON-AUTUMN days in seatle 2014:  0.32010284428732116


In [6]:
import numpy as np
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]
